main: deimophobe.dvz.DvZPlugin
name: CustomDvZ
version: 1.0
author: Deimo
description: Deimo's custom dvz thing
depend: [ProtocolLib]
commands:
  setdwarf:
    usage: /setdwarf <name> [<sword> <bow> <ale> <armour> <title>]
  setmob:
    usage: /setmob <name>
  spawnmob:
    usage: /spawnmob <name> <mobtype>
  removeplayer:
    usage: /removeplayer <name>

  horn:
    usage: /horn
    description: HRON
  armour:
    description: Cheaty self-armour.

  trash:
    description: For deleting your duplicate items.
    aliases: fawn
  chest:
    description: For sharing resources with your fellow dwarves.
  loadout:
    description: Choose a kit!
    aliases: kit
  stuck:
    description: For when you're stuck.
  who:
    description: Who is what and where is why
    aliases: list

  toggleais:
    usage: /toggleais
    description: Enables/disables AI spawning.
  toggledoom:
    usage: /toggledoom
    description: Enables/disables doom clock.

  forcestart:
    description: Forces the game to start.
  forceplague:
    description: Forces the plague to occur.