main: deimophobe.nightfall.lobby.NightfallLobbyPlugin
name: Nightfall-Lobby
version: 0.1
author: Deimophobe
description: The plugin for the Nightfall lobby.
depend: [NightfallCommon, SubServers-Client-Bukkit]

commands:
  loadout:
    description: Choose a kit!
    aliases: kit