# Main folder with all the stuff - relative to home
nightfall-folder: Nightfall/Server

# All other paths are relative to nightfall-folder


lobby:
  jar: spigot-1.12.jar
  src-folder: Lobby

nightfall:
  jar: spigot-1.12.jar
  src-folder: Nightfall
  run-folder-prefix: Nightfall


template-folder: Template
run-folder: Running
