main: deimophobe.dvz.DvZPlugin
name: CustomDvZ
version: 1.0
author: Deimo
description: Deimo's custom dvz thing
depend: [ProtocolLib]
commands:
  setdwarf:
    usage: /setdwarf <name> [ item1 item2 ... ]
    description: Sets a player to be a dwarf.
  sethero:
    usage: /sethero <name> <herotype>
    description: Sets a player to be a hero.
  setmob:
    usage: /setmob <name>
    description: Sets a player to be a mob
  spawnmob:
    usage: /spawnmob <name> <mobtype>
    description: Forces a player to spawn as a mob
  removeplayer:
    usage: /removeplayer <name>
    description: Removes a player (from both dwarf and mob).

  horn:
    usage: /horn
    description: HRON
  armour:
    usage: /armour equip | /armour [damage|repair] <amount>
    description: Cheaty self-armour.
    alias: armor
  giveitem:
    usage: /giveitem <item-name>
    description: Give a custom item to yourself.

  trash:
    description: For deleting your duplicate items.
    aliases: fawn
  chest:
    description: For sharing resources with your fellow dwarves.
  loadout:
    description: Choose a kit!
    aliases: kit
  stuck:
    description: For when you're stuck (before the game starts).
  who:
    description: Who is what and where is why
    aliases: list

  toggleais:
    description: Enables/disables AI spawning.
    usage: /toggleais
  toggledoom:
    description: Enables/disables doom clock.
    usage: /toggledoom

  forcestart:
    description: Forces the game to start.
    usage: /forcestart
  forceplague:
    description: Forces the plague to occur.
    usage: /forceplague
  plagueimmune:
    description: Makes a player (un)immune to plague.
    usage: /plagueimmune [player]

  loadmap:
    description: Loads a specified map.
    usage: /loadmap <mapname>
  enableMapLoading:
    description: Allows maps to be loaded. Causes reloads to kick people.
    usage: /enableMapLoading
  disableMapLoading:
    description: Disables map loading. Game will be played on default map instead.
    usage: /disableMapLoading

  kills:
    description: Only for toxic people.
    usage: /kills

