# Does nothing yet - but might be useful to add at some point.
debug: true

database:
  # Valid options: flat, mongo, none (default)
  # Note that 'none' will not save any data.
  type: flat

  mongo:
    host: localhost
    database: nightfall