# Does nothing yet - but might be useful to add at some point.
debug: false

database:
  # Valid options: flat, mongo, none (default)
  # Note that 'none' will not save any data.
  type: flat

  # Autosave frequency in seconds (default 5 mins). A value of -1 will disable.
  autosave: 10

  # Only read if type is 'mongo'
  mongo:
    host: localhost
    database: nightfall