main: deimophobe.nightfall.common.NightfallCommonPlugin
name: NightfallCommon
version: 0.1
author: Deimophobe
description: The common library plugin for the nightfall game.
depend: [LibsDisguises, ProtocolLib, LuckPerms]
api-version: 1.13

permissions:
  nightfall.maintenance.join:
    description: Allows player to join while in maintenance mode.
    default: op